#!/bin/sh

# This entire block is a hack.
gateway="zzzzzzzzzzzzzz"
while getopts g op; do
	case "$op" in
	g)
		# If -g is used, then don't delete the gateway's ARP entry.
		gateway="`route -n | grep "UG" | awk '{print $2}'`"
	;;
	esac
done

# Enumerate and delete all the entries.
list="`arp -n | tail -n +2 | grep -v $gateway | awk '{print $1}'`"
for host in $list ; do
	arp -d "$host"
done
