#!/bin/sh

# If the description is not explicitly provided, then command will be used in its place.

if [ -z "$1" ]; then
	echo "Usage: $0 <command> [description]"
	exit 1
fi

CMD="$1"
DESCR="$2"
[ "$DESCR" = "" ] && DESCR="$1"

zenity --question --text="Are you sure you want to $DESCR?" --ok-label=Yes --cancel-label=No

[ $? -eq 0 ] && exec $1
