#!/bin/sh

# From: http://www.troubleshooters.com/linux/coasterless.htm

device=$1

blocksize=`isoinfo -d -i $device | grep "^Logical block size is:" | cut -d " " -f 5`
if test "$blocksize" = ""; then
	echo catdevice FATAL ERROR: Blank blocksize >&2
	exit
fi

blockcount=`isoinfo -d -i $device | grep "^Volume size is:" | cut -d " " -f 4`
if test "$blockcount" = ""; then
	echo catdevice FATAL ERROR: Blank blockcount >&2
	exit
fi

command="dd if=$device of="$2" bs=$blocksize count=$blockcount conv=notrunc,noerror"
echo "$command" >&2
$command & pid=$!
echo

progress=`ps $pid`
while [ ! -z "$progress" ]; do
	sleep 5
	kill -USR1 $pid
	progress=`ps $pid`
done
