#!/bin/sh

if [ ! -x `which scrot` ]; then
	echo "This script requires 'scrot' to run. Please ensure it is available." >&2
	exit 1
fi

if [ ! -x `which zenity` ]; then
	echo "This script requires 'zenity' to run. Please ensure it is available." >&2
	exit 1
fi

DATE="`date +%m-%d_%H:%M:%S`"
DEFAULT_FILENAME="screenshot-$DATE.png"

scrot "$DEFAULT_FILENAME" -e 'mv $f /tmp/'
FILENAME="`zenity --entry --text=\"Screenshot saved! Please choose a file name (and optionally the absolute path).\n(Press Cancel to delete the screenshot.)" --entry-text="$DEFAULT_FILENAME\"`"

# Delete the screenshot if it's a blank filename.
if [ "$FILENAME" = "" ]; then
	rm /tmp/$DEFAULT_FILENAME
# If a path was provided, treat it as absolute.
elif [ "`dirname "$FILENAME"`" != "." ]; then
	mv "/tmp/$DEFAULT_FILENAME" "$FILENAME"
#Otherwise, move it to the Desktop.
else
	mv "/tmp/$DEFAULT_FILENAME" "/home/b-con/Desktop/$FILENAME"
fi

