#!/bin/sh

if [ "$EUID" -ne "0" ]; then
	echo "You must run as root." >&2
fi

case "$1" in
opendns)
	echo "nameserver 208.67.222.222" >  /etc/resolv.conf
	echo "nameserver 208.67.220.220" >> /etc/resolv.conf
;;
google)
	echo "nameserver 8.8.8.8" >  /etc/resolv.conf
	echo "nameserver 8.8.4.4" >> /etc/resolv.conf
;;
*)
	echo "Specify which DNS setting to use." >&2
	echo "   opendns" >&2
	echo "   google" >&2
esac
