#!/bin/sh
# By: Brad Conte <brad@bradconte.com>

if [ $# -ne 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "Usage: $0 [filename]" >&2
	echo "    where 'filename' is the full path to the file you wish to recover." >&2
	echo "    This script will look for open file handles to the file and attempt" >&2
	echo "to use them to restore the file. The restored file will have a" >&2
	echo "different inode number, so existing file handles and hard links will" >&2
	echo "need to be updated if they need to use the new file." >&2
	exit -1
fi

if [ -f "$1" ]; then
	echo "File already exists." >&2
	exit -1
fi


LIST="`lsof | grep "$1" | grep "(deleted)"`"
LIST_SIZE=`echo -e "$LIST" | wc -l`
if [ $LIST_SIZE -eq 0 ]; then
	echo "No processes found with an open file handle to a deleted $1." >&2
	[ $EUID -ne 0 ] && echo "You may want to try escalating priviledges." >&2
	exit -1
fi

SUCCESS=0
FOUND=0
BAD_PERM=0
idx=1
while [ $idx -le $LIST_SIZE -a $SUCCESS -ne 1 ]; do
	LINE="`echo -e "$LIST" | head -n $idx | tail -n 1`"
	PID=`echo "$LINE" | awk '{print $2}'`
	FD="`echo "$LINE" | awk '{print $4}' | sed -e 's/[^0-9]//g'`"
	FILE="/proc/$PID/fd/$FD"

	if [ -f "$FILE" ]; then
		FOUND=1
		if [ -r "$FILE" ]; then
			if [ ! -d "`dirname $1`" ]; then
				echo "Destination directory does not exist." >&2
				exit -1
			fi
			if [ ! -w "`dirname $1`" ]; then
				echo "Insufficient permissions to write to destination directory." >&2
				exit -1
			fi

			cp --preserve=all "$FILE" "$1"
			[ -f "$1" ] && SUCCESS=1
		else
			BAD_PERM=1
		fi
	fi
	idx=$(( $idx + 1))
done

if [ $SUCCESS -eq 0 ]; then
	if [ $FOUND -eq 0 ]; then
		echo "Sorry, could not find the file still open in any of the available file handles." >&2
		exit -1
	elif [ $BAD_PERM -eq 1 ]; then
		echo "Found recoverable file but did not have permissions to read it." >&2
		exit -1
	fi
fi

exit 0
