#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" ]; then
	echo "usage: update-arch [-o -a]"
	exit 1
fi

if [ $EUID != "0" ]; then
	echo "Please run as root" >&2
	exit 1
fi

# Determine the size of the current log file
LOG_FILE="/var/log/pacman.log"
LOG_SIZE=`wc -l $LOG_FILE | cut -d ' ' -f 1`

# Get the last update time
LAST_UPGRADE_TIME=`grep "starting full system upgrade" /var/log/pacman.log | tail -n 1 | cut -d '[' -f 2 | cut -d ']' -f 1`

# Update the system
pacman -Sy || exit 1
pacman -S pacman --needed || exit 1   # pacman must be updated first
pacman -Su || exit 1

# Remove orphaned packages
pacman -Qdt | cut -d ' ' -f 1 | xargs pacman --noconfirm -Rs

# Optimize the pacman database if instructed to
[ "$1" = "--optimize" -o "$1" = "-o" ] && pacman-optimize

# Update ABS
abs
sync

# Find any new .pacnew/.pacsave files, warnings, or removed packages
LOG=`tail -n +$(( LOG_SIZE + 1 )) $LOG_FILE`
MESSAGES=`echo "$LOG" | grep -v '[PACMAN] removed ' | grep -v '] installed ' | \
                        grep -v '[PACMAN] upgraded ' | grep -v '] Running ' | \
						grep -v '[PACMAN] synchronizing ' | grep -v '] starting '`
REMOVED="`echo "$LOG" | grep '[PACMAN] removed ' | awk '{print $5}'`"
PACNEWS="`find /etc/ -name \*.pacnew 2> /dev/null`"

# Finish
echo
echo "-> FINISHED"
echo "-> Pacman database updated"
echo "-> Installed packages updated"
echo "-> Orphaned packages removed"
[ "$1" = "--optimize" -o "$1" = "-o" ] && echo "-> Pacman database optimized"
echo "-> ABS updated"
if [ ! -z "$MESSAGES" ]; then
	echo "-> pacman output the following messages:"
	echo "--------------------------------------------------------------"
	echo "$MESSAGES"
	echo "--------------------------------------------------------------"
fi
if [ ! -z "$REMOVED" ]; then
	echo "-> pacman removed the following packages (possibly due to being orphaned):"
	echo "$REMOVED"
fi
if [ ! -z "$PACNEWS" ]; then
	echo "-> The following .pacnew/.pacsave files exist in /etc:"
	echo "$PACNEWS"
fi
if [ ! -z "$LAST_UPGRADE_TIME" ]; then
	echo "-> The last time you upgraded was at $LAST_UPGRADE_TIME"
fi

